// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_batch.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const batchDeleteURLs = `-- name: BatchDeleteURLs :exec
UPDATE urls SET is_deleted = true
WHERE user_id = $1 AND short_url = ANY($2::text[])
`

type BatchDeleteURLsParams struct {
	UserID  sql.NullString
	Column2 []string
}

func (q *Queries) BatchDeleteURLs(ctx context.Context, arg BatchDeleteURLsParams) error {
	_, err := q.db.ExecContext(ctx, batchDeleteURLs, arg.UserID, pq.Array(arg.Column2))
	return err
}
