// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_url.sql

package queries

import (
	"context"
	"database/sql"
)

const insertOrGetShortURL = `-- name: InsertOrGetShortURL :one
INSERT INTO urls (short_url, original_url, user_id, is_deleted)
VALUES ($1, $2, $3, false)
ON CONFLICT (original_url) DO NOTHING
RETURNING short_url
`

type InsertOrGetShortURLParams struct {
	ShortUrl    string
	OriginalUrl string
	UserID      sql.NullString
}

func (q *Queries) InsertOrGetShortURL(ctx context.Context, arg InsertOrGetShortURLParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertOrGetShortURL, arg.ShortUrl, arg.OriginalUrl, arg.UserID)
	var short_url string
	err := row.Scan(&short_url)
	return short_url, err
}
