// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Url struct {
	ID          int32
	ShortUrl    string
	OriginalUrl string
	UserID      sql.NullString
}
