// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select_by_original.sql

package queries

import (
	"context"
)

const getByOriginalURL = `-- name: GetByOriginalURL :one
SELECT short_url FROM urls WHERE original_url = $1 AND is_deleted = false
`

func (q *Queries) GetByOriginalURL(ctx context.Context, originalUrl string) (string, error) {
	row := q.db.QueryRowContext(ctx, getByOriginalURL, originalUrl)
	var short_url string
	err := row.Scan(&short_url)
	return short_url, err
}
